name: Build and Publish

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build-sources:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    
    - name: Install dependencies
      run: dotnet restore ./src/FoodOrderSystem.App
    
    - name: Build
      run: dotnet build --configuration Release --no-restore ./src/FoodOrderSystem.App
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal ./src/FoodOrderSystem.App
    
    - name: Publish
      run: dotnet publish --configuration Release --no-restore --no-build ./src/FoodOrderSystem.App
    
    - name: Stash package
      uses: actions/upload-artifact@v1
      with:
        name: package
        path: ./src/FoodOrderSystem.App/bin/Release/netcoreapp3.1/publish/

  
  build-docker:
    runs-on: ubuntu-latest
    needs: build-sources

    steps:
    - uses: actions/checkout@v2
  
    - name: Unstash package
      uses: actions/download-artifact@v1
      with:
        name: package
        path: ./src/FoodOrderSystem.App/bin/Release/netcoreapp3.1/publish/
    
    - name: Build docker image (Push)
      if: ${{ github.event_name == 'push' }}
      run: docker build --no-cache --tag food_order_system:${GITHUB_REF#refs/heads/} .
    
    - name: Build docker image (Pull Request)
      if: ${{ github.event_name == 'pull_request' }}
      run: docker build --no-cache --tag food_order_system:${GITHUB_HEAD_REF#refs/heads/} .